id: PB6C06F8A
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: es
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    3112e9ba1ae341559feaa3724d4896bb:
      title: Advice for Alak Dongak
      parent: Advice
    88c48ab868114937a723e076d6b6bb9e:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    10fa4edc400c4bb1a1cd52a1b1976794:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    449dc67d03aa49749436f33bbea8b12d:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    6c3c4745bd8547c8becee7189938af57:
      title: Yearning for Mountain Solitude
      parent: Advice
    c6df2612f876406fbe7faa64127121e4:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    211de04754e24135984a18bc6e833221:
      title: Biography of Patrul Rinpoche
      parent: Biography
    0c78ac460dc34be4a6c10ae8ae3c4ff5:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    e83f1f8000a440788acb886606a6eff4:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    af11755fa4024270a400aab086d2bbcb:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    e20cc1bf94fb44538e8e2cad68f0019b:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    01ee4304fff641538a0e87ec4c938580:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    039125c5c838468a9014a5cd0275ccdb:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    5abb5d8840204956911a604f44de8ddd:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    8d748da024ce4ea49986f9d830cdd98f:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    6fc311a9ebc14d3085d058542f52b769:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    a0da0c96e596479db620d74c9cc2806a:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    1d53f5bc4fb348e7a0a2bf882afd17fe:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    e608c41abc9a4717a974a463fe693773:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    c523e93a98a945a6afde46361dcaf3cf:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    fcf07718e4a84a5ea8b7364a097b3f6e:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    8ffa694766ae43bba00f70b9bad4cf73:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    341761048d6047e7966ec41d1a36f395:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    c3112cf1eab942e88d838062ee0a4730:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    cdf7c89a63d24a51a293dcb980456943:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    6891f06a1b5f44a79ce9d6eee53ea0f4:
      title: Prayer to Machik Labdrön
      parent: Prayers
    f476a05005be4cfcb2e4f47c9f76d7be:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    274f7f2588d24315bbfc6a0cd7b5782e:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    37907c36a8bc4b3bba88dc54f548880f:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    17361139502f43f388f648fcf6111779:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    e123eabc735649f79ec960071ce4c925:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    49ed00f7de814ecab533552c83bda82c:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    e5958c40b1d14883a82298ddd0007af6:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    be2dc223e8fa44f5ac62631403b3a3b5:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    baa938322b7947dbb8ca9c04aa78c01a:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    4c7b9c1f31ee4f12b65e829027c3c2e9:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    a07557aeec0c4b8a90835b26d3b3ed21:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    370664a0ee6246e493ee8b68481c78af:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    338671963c4b4b6ab1e7cee8d4456f12:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.742522'
last_modified_at: '2022-03-01T01:13:56.742524'
